services:
  calcurates-demo-php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: calcurates-demo-php
    environment:
      PHP_IDE_CONFIG: "serverName=calcurates-demo"
      XDEBUG_SESSION: docker-server
    volumes:
      - ./:/var/www:rw
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - calcurates-demo-sqlite
    networks:
      - calcurates-demo-network

  calcurates-demo-nginx:
    image: nginx:alpine
    container_name: calcurates-demo-nginx
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - calcurates-demo-network

  calcurates-demo-sqlite:
    image: hibitdev/sqlite:latest
    container_name: calcurates-demo-sqlite
    hostname: sqlite.hibit
    ports:
      - "8191:8191"
    volumes:
      - ./sqlite:/db
    command: [ "tail", "-f", "/dev/null" ]
    networks:
      - calcurates-demo-network

networks:
  calcurates-demo-network:
    driver: bridge
